import { MessageCircle, Send, ArrowLeftRight } from 'lucide-react';
import type { WorkflowConfig } from '../BusinessSlidersTab';

interface TokenControlsProps {
  workflow: WorkflowConfig;
  onUpdate: (updates: Partial<WorkflowConfig>) => void;
}

export default function TokenControls({ workflow, onUpdate }: TokenControlsProps) {
  const controls = [
    {
      key: 'avg_input_tokens' as keyof WorkflowConfig,
      label: 'Average Input Tokens',
      icon: MessageCircle,
      min: 100,
      max: 50000,
      step: 100,
      value: workflow.avg_input_tokens,
      description: 'Tokens sent to the model per transaction',
    },
    {
      key: 'avg_output_tokens' as keyof WorkflowConfig,
      label: 'Average Output Tokens',
      icon: Send,
      min: 100,
      max: 20000,
      step: 100,
      value: workflow.avg_output_tokens,
      description: 'Tokens generated by the model per transaction',
    },
    {
      key: 'inter_agent_tokens' as keyof WorkflowConfig,
      label: 'Inter-Agent Tokens',
      icon: ArrowLeftRight,
      min: 0,
      max: 10000,
      step: 100,
      value: workflow.inter_agent_tokens,
      description: 'Tokens exchanged between agents',
    },
  ];

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
      <h2 className="text-xl font-bold text-black mb-6 flex items-center gap-2">
        <MessageCircle className="h-5 w-5" />
        Token Usage Controls
      </h2>
      <div className="space-y-6">
        {controls.map((control) => (
          <div key={control.key}>
            <div className="flex items-center justify-between mb-2">
              <div className="flex-1">
                <label className="flex items-center gap-2 text-sm font-medium text-gray-700">
                  <control.icon className="h-4 w-4" />
                  {control.label}
                </label>
                <p className="text-xs text-gray-500 mt-0.5 ml-6">{control.description}</p>
              </div>
              <div className="flex items-center gap-2">
                <input
                  type="number"
                  value={control.value}
                  onChange={(e) => onUpdate({ [control.key]: parseInt(e.target.value) || 0 })}
                  className="w-24 px-3 py-1 border border-gray-300 rounded-lg text-sm text-right focus:ring-2 focus:ring-black focus:border-transparent"
                  min={control.min}
                  max={control.max}
                  step={control.step}
                />
                <span className="text-xs text-gray-500 w-12">tokens</span>
              </div>
            </div>
            <input
              type="range"
              value={control.value}
              onChange={(e) => onUpdate({ [control.key]: parseInt(e.target.value) })}
              min={control.min}
              max={control.max}
              step={control.step}
              className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer slider-thumb"
            />
            <div className="flex justify-between text-xs text-gray-500 mt-1">
              <span>{control.min.toLocaleString()}</span>
              <span>{control.max.toLocaleString()}</span>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 p-4 bg-gray-50 rounded-lg border border-gray-200">
        <h3 className="text-sm font-semibold text-black mb-2">Token Guidance</h3>
        <ul className="text-xs text-gray-600 space-y-1">
          <li>• <strong>Input:</strong> Context + prompt (typically 1K-5K for simple tasks)</li>
          <li>• <strong>Output:</strong> Generated response (typically 500-2K tokens)</li>
          <li>• <strong>Inter-Agent:</strong> Communication between agents in multi-agent systems</li>
        </ul>
      </div>
    </div>
  );
}
